apiVersion: v1
kind: Service
metadata:
  name: webclient-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: webclient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000